-- Seed skills for Autopus Marketplace Launch
-- Run this SQL directly on the database

INSERT INTO "Skill" (id, slug, name, description, category, icon, version, tier, "priceUsd", featured, installs, manifest, "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'email-ninja', 'Email Ninja', 'Automatically summarize, prioritize, and draft emails. Works with Gmail, Outlook, and any IMAP inbox. Learns your writing style over time.', 'productivity', '📧', '1.0.0', 'FREE', NULL, true, 0, '{"triggers":["email","inbox","message","draft"],"actions":["summarize","prioritize","draft","schedule-send"],"permissions":["email.read","email.send"],"config":{"summaryLength":"medium","autoDraft":false,"workingHours":{"start":9,"end":18}}}', NOW(), NOW()),

(gen_random_uuid(), 'calendar-sage', 'Calendar Sage', 'Smart scheduling that finds the best meeting times, prepares agendas, and sends reminders. Integrates with Google Calendar, Calendly, and Outlook.', 'productivity', '📅', '1.0.0', 'FREE', NULL, true, 0, '{"triggers":["meeting","schedule","calendar","appointment"],"actions":["find-slots","book","remind","prepare-agenda"],"permissions":["calendar.read","calendar.write"],"config":{"bufferMinutes":15,"preferredTimes":["09:00","14:00"],"autoDecline":false}}', NOW(), NOW()),

(gen_random_uuid(), 'task-master', 'Task Master', 'Intelligent task management that captures todos from conversations, sets priorities, and tracks completion. Syncs with Todoist, Notion, and Asana.', 'productivity', '✅', '1.0.0', 'FREE', NULL, false, 0, '{"triggers":["todo","task","remind me","dont forget"],"actions":["capture","prioritize","schedule","follow-up"],"permissions":["tasks.read","tasks.write"],"config":{"defaultPriority":"medium","autoSchedule":true,"reminderPolicy":"smart"}}', NOW(), NOW()),

(gen_random_uuid(), 'lead-hunter', 'Lead Hunter', 'Find and enrich prospect information from LinkedIn, Apollo, and Hunter. Automatically builds lead lists and tracks outreach.', 'business', '🎯', '1.0.0', 'PREMIUM', 9, true, 0, '{"triggers":["lead","prospect","contact","outreach"],"actions":["search","enrich","verify","track"],"permissions":["api.apollo","api.hunter","api.linkedin"],"config":{"dailyLimit":100,"enrichmentLevel":"full","autoVerify":true}}', NOW(), NOW()),

(gen_random_uuid(), 'meeting-scribe', 'Meeting Scribe', 'Joins your Zoom/Meet calls, transcribes conversations, extracts action items, and generates summaries. Never take notes again.', 'business', '📝', '1.0.0', 'PREMIUM', 12, true, 0, '{"triggers":["meeting","call","zoom","transcribe"],"actions":["join","record","transcribe","summarize","extract-actions"],"permissions":["calendar.read","meetings.join"],"config":{"autoJoin":true,"summaryStyle":"detailed","extractDecisions":true}}', NOW(), NOW()),

(gen_random_uuid(), 'tweet-stormer', 'Tweet Stormer', 'Creates engaging Twitter threads from your ideas. Analyzes your best-performing content to match your voice and optimize engagement.', 'creative', '🐦', '1.0.0', 'FREE', NULL, false, 0, '{"triggers":["twitter","thread","tweet","social"],"actions":["draft","optimize","schedule","analyze"],"permissions":["twitter.read","twitter.write"],"config":{"tone":"professional","threadLength":"medium","autoSchedule":false}}', NOW(), NOW()),

(gen_random_uuid(), 'content-calendar', 'Content Calendar', 'Plans, schedules, and publishes content across platforms. Maintains consistent posting schedules and tracks performance.', 'creative', '📆', '1.0.0', 'PREMIUM', 7, false, 0, '{"triggers":["content","post","schedule","publish"],"actions":["plan","draft","schedule","publish","analyze"],"permissions":["buffer","instagram","linkedin","twitter"],"config":{"platforms":["twitter","linkedin"],"postingTimes":["09:00","14:00","18:00"],"autoHashtag":true}}', NOW(), NOW()),

(gen_random_uuid(), 'code-reviewer', 'Code Reviewer', 'Analyzes pull requests for bugs, security issues, and style violations. Learns your team''s coding standards over time.', 'development', '💻', '1.0.0', 'FREE', NULL, true, 0, '{"triggers":["PR","pull request","review","code"],"actions":["analyze","comment","suggest","approve"],"permissions":["github.read","github.write"],"config":{"checkSecurity":true,"checkPerformance":true,"styleGuide":"standard"}}', NOW(), NOW()),

(gen_random_uuid(), 'vps-guardian', 'VPS Guardian', 'Monitors server health, alerts on anomalies, and suggests optimizations. Works with any VPS provider via SSH.', 'development', '🖥️', '1.0.0', 'PREMIUM', 5, true, 0, '{"triggers":["server","vps","health","monitor"],"actions":["monitor","alert","optimize","report"],"permissions":["ssh.read","system.metrics"],"config":{"checkInterval":60,"alertThreshold":{"cpu":80,"memory":85,"disk":90},"autoOptimize":false}}', NOW(), NOW()),

(gen_random_uuid(), 'web-search-pro', 'Web Search Pro', 'Deep web research with source verification, summary generation, and fact-checking. Cites sources in every answer.', 'research', '🔍', '1.0.0', 'FREE', NULL, true, 0, '{"triggers":["search","research","find","look up"],"actions":["search","verify","summarize","cite"],"permissions":["search.api","web.read"],"config":{"resultCount":10,"recency":"month","verifyFacts":true,"citeSources":true}}', NOW(), NOW()),

(gen_random_uuid(), 'finance-tracker', 'Finance Tracker', 'Tracks expenses, monitors budgets, and generates financial reports. Connects to bank accounts and crypto wallets.', 'business', '💰', '1.0.0', 'PREMIUM', 8, false, 0, '{"triggers":["expense","budget","finance","money"],"actions":["track","categorize","report","alert"],"permissions":["bank.read","crypto.read"],"config":{"budgetAlerts":true,"reportFrequency":"weekly","currency":"USD"}}', NOW(), NOW()),

(gen_random_uuid(), 'memory-boost', 'Memory Boost', 'Enhanced memory system that automatically organizes information, creates connections, and surfaces relevant context.', 'productivity', '🧠', '1.0.0', 'FREE', NULL, true, 0, '{"triggers":["remember","recall","what did","when did"],"actions":["store","organize","connect","recall"],"permissions":["memory.read","memory.write"],"config":{"autoOrganize":true,"connectionDepth":3,"contextWindow":"unlimited"}}', NOW(), NOW());

-- Verify insertion
SELECT category, tier, COUNT(*) as count FROM "Skill" GROUP BY category, tier;
